// <auto-generated />
using System;
using CommercialManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommercialManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903110224_AddUtilisateursTable")]
    partial class AddUtilisateursTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Date_de_création")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prénom_ou_raison_sociale")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Téléphone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Identifiant");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Commande", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Client_associé")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_de_commande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Numéro_de_commande")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Statut_de_la_commande")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Total_HT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total_TTC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Identifiant");

                    b.HasIndex("Client_associé");

                    b.HasIndex("Numéro_de_commande")
                        .IsUnique();

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Ligne_de_commande", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Commande_Identifiant")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix_unitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Produit_Identifiant")
                        .HasColumnType("int");

                    b.Property<int>("Quantité")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_ligne")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Identifiant");

                    b.HasIndex("Commande_Identifiant");

                    b.HasIndex("Produit_Identifiant");

                    b.ToTable("Lignes_de_commande");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Produit", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_de_création")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nom_du_produit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Prix_unitaire_HT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantité_en_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Référence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identifiant");

                    b.HasIndex("Référence")
                        .IsUnique();

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Identifiant");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Commande", b =>
                {
                    b.HasOne("CommercialManagement.Domain.Entities.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("Client_associé")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Ligne_de_commande", b =>
                {
                    b.HasOne("CommercialManagement.Domain.Entities.Commande", "Commande")
                        .WithMany("Lignes_de_commande")
                        .HasForeignKey("Commande_Identifiant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommercialManagement.Domain.Entities.Produit", "Produit")
                        .WithMany("Lignes_de_commande")
                        .HasForeignKey("Produit_Identifiant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Commande", b =>
                {
                    b.Navigation("Lignes_de_commande");
                });

            modelBuilder.Entity("CommercialManagement.Domain.Entities.Produit", b =>
                {
                    b.Navigation("Lignes_de_commande");
                });
#pragma warning restore 612, 618
        }
    }
}
